name: Deploy MEAN Stack to Linode

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest # The runner environment
    environment: production # Optional: for environment-specific secrets/protections

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 # Use the official Terraform setup action
        with:
          terraform_version: 1.x.x # Specify your desired Terraform version (e.g., 1.7.5)

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform # Assuming your Terraform files are in a 'terraform' directory

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./terraform
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_API_TOKEN }} # Pass Linode API token
          TF_VAR_ssh_public_key: ${{ secrets.LINODE_SSH_PUBLIC_KEY }} # Pass SSH Public Key

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_API_TOKEN }}
          TF_VAR_ssh_public_key: ${{ secrets.LINODE_SSH_PUBLIC_KEY }}

      - name: Get Linode IP Address
        id: get_ip # Assign an ID to reference this step's outputs
        run: |
          LINODE_IP=$(terraform output -raw ip_address)
          echo "LINODE_IP=$LINODE_IP" >> $GITHUB_ENV # Make IP available as an environment variable for subsequent steps
          echo "ip_address=$LINODE_IP" >> $GITHUB_OUTPUT # Make IP available as a step output
        working-directory: ./terraform
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_API_TOKEN }} # Still needed for Terraform output

  configure_server:
    runs-on: ubuntu-latest
    needs: deploy_infrastructure
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key for Ansible
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
          log-public-key: true

      - name: Wait for SSH (TCP Port 22) on Linode VM
        uses: jakejarvis/wait-for-it-action@master
        with:
          host: ${{ env.LINODE_IP }}:22 # Will resolve to 172.105.116.224:22 at runtime
          timeout: 300
          check-interval: 5
        env:
          LINODE_IP: ${{ env.LINODE_IP }} # The IP from deploy_infrastructure job

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create Ansible inventory file
        run: |
          echo "[mean_servers]" > inventory.ini
          echo "${{ env.LINODE_IP }} ansible_user=root" >> inventory.ini # 172.105.116.224 will be used here
        env:
          LINODE_IP: ${{ env.LINODE_IP }}

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini main.yml --extra-vars "git_repo_url=git://github.com/lukemartin35/PanlasAppServer.git"
        working-directory: ./ansible
