name: Deploy MEAN Stack to Linode

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    environment: production # <--- Both jobs will use the 'production' environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x # Specify your desired Terraform version (e.g., 1.7.5)

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./terraform
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_API_TOKEN }}
          TF_VAR_ssh_public_key: ${{ secrets.LINODE_SSH_PUBLIC_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_API_TOKEN }}
          TF_VAR_ssh_public_key: ${{ secrets.LINODE_SSH_PUBLIC_KEY }}

      - name: Get Linode IP Address
        id: get_ip
        run: |
          LINODE_IP=$(terraform output -raw ip_address)
          echo "LINODE_IP=$LINODE_IP" >> $GITHUB_ENV
          echo "ip_address=$LINODE_IP" >> $GITHUB_OUTPUT
        working-directory: ./terraform
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_API_TOKEN }}

  configure_server:
    runs-on: ubuntu-latest
    needs: deploy_infrastructure
    environment: production # <--- Both jobs will use the 'production' environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key for Ansible
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
          log-public-key: true

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create Ansible inventory file
        run: |
          echo "[mean_servers]" > inventory.ini
          echo "${{ env.LINODE_IP }} ansible_user=root" >> inventory.ini
        env:
          LINODE_IP: ${{ env.LINODE_IP }}

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini main.yml --extra-vars "git_repo_url=git://github.com/lukemartin35/PanlasAppServer.git"
        working-directory: ./ansible